<?php
use ConLayout\Layout\LayoutInterface;
$blockId = $block->getOption('block_id');
$esiUrl = $this->esiUrl($blockId, $this->__HANDLES__);
?>
<?php if ($this->__DEBUG__): ?>
<!--
    [ ESI START: <?= $blockId ?> ]
    [ TTL: <?= $this->__TTL__ ?> ]
<?php if (count($this->__HANDLES__)): ?>
    [ Handles: <?= implode(', ', array_keys($this->__HANDLES__)) ?> ]
<?php endif ?>
<?php if (count($this->__TAGS__)): ?>
    [ Ban-Tags: <?= implode(', ', $this->__TAGS__) ?> ]
<?php endif ?>
    [ Ban-Url: <?= $esiUrl ?> ]
-->
<?php endif; ?>
<esi:include src="<?= $esiUrl  ?>"/>
<esi:remove>
    <?= $this->content ?>
</esi:remove>
<?php if ($this->__DEBUG__): ?>
<!-- [ ESI STOP: <?= $blockId ?> ] -->
<?php endif; ?>
