language: php

php:
  - 7.3
  - 7.4
  
before_script:
  - composer self-update
  - composer update --prefer-dist
  
script:
  - ./vendor/bin/phpunit --coverage-clover ./build/logs/clover.xml
  - ./vendor/bin/phpcs --standard=PSR12 ./src/ ./tests/

after_script:
  - ./vendor/bin/coveralls -v
